### ISSUE TITLE
Invalid `memcpy` in `igl::MshLoader::parse_nodes`

### ISSUE THREAD

**Issue by sudhackar** [libigl/libigl#1982]
While writing a fuzz target for `MshLoader` based on [oss-fuzz](https://github.com/google/oss-fuzz/tree/master/projects/libigl) and [libprotobuf-mutator](https://github.com/google/libprotobuf-mutator) this is the first crash that I hit instantly.
```
[#0] Id 1, Name: "101_FileIO", stopped 0x7ffff7012a88 in __memmove_avx_unaligned_erms (), reason: SIGSEGV
gef➤  bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:301
#1  0x0000000000404c6e in igl::MshLoader::parse_nodes (this=0x7fffffffdf90, fin=...) at /home/sudhakar/fuzz/libigl/include/igl/MshLoader.cpp:135
#2  0x000000000040463b in igl::MshLoader::MshLoader (this=0x7fffffffdf90, filename=Python Exception <class 'gdb.error'> There is no member named _M_dataplus.:
) at /home/sudhakar/fuzz/libigl/include/igl/MshLoader.cpp:93
#3  0x0000000000402502 in main (argc=0x2, argv=0x7fffffffe248) at /home/sudhakar/fuzz/libigl/tutorial/101_FileIO/main.cpp:13
gef➤  x/5xi $rip
=> 0x7ffff7012a88 <__memmove_avx_unaligned_erms+120>:   vmovdqu XMMWORD PTR [rdi],xmm0
   0x7ffff7012a8c <__memmove_avx_unaligned_erms+124>:   vmovdqu XMMWORD PTR [rdi+rdx*1-0x10],xmm1
   0x7ffff7012a92 <__memmove_avx_unaligned_erms+130>:   ret
   0x7ffff7012a93 <__memmove_avx_unaligned_erms+131>:   mov    rcx,QWORD PTR [rsi+rdx*1-0x8]
   0x7ffff7012a98 <__memmove_avx_unaligned_erms+136>:   mov    rsi,QWORD PTR [rsi]
gef➤  i r rdi
rdi            0x16ab93058      0x16ab93058
```
Looking at the comments https://github.com/libigl/libigl/blob/66b3ef2253e765d0ce0db74cec91bd706e5ba176/include/igl/MshLoader.cpp#L134

I tried to change 101_FileIO to the following code 

```cpp
#include <igl/MshLoader.h>
#include <iostream>

int main(int argc, char *argv[])
{
  if (argc < 2)
  {
    puts("msh file in argv[1] expected");
    return -1;
  }
  printf("%ld:%ld\n", sizeof(double), sizeof(igl::MshLoader::Float));
  try
  {
    igl::MshLoader msh_loader(argv[1]);
  }
  catch (const std::exception &exc)
  {
    std::cerr << exc.what();
  }
}
```

Both `sizeof(double)` and `sizeof(igl::MshLoader::Float)` print 8 as is the asan output here
```
8:8
AddressSanitizer:DEADLYSIGNAL
=================================================================
==18854==ERROR: AddressSanitizer: SEGV on unknown address 0x60316a567b58 (pc 0x7fa430f3725f bp 0x7ffd328b31f0 sp 0x7ffd328b29a8 T0)
==18854==The signal is caused by a WRITE memory access.
    #0 0x7fa430f3725f in memcpy /build/glibc-S9d2JN/glibc-2.27/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:145
    #1 0x494df7 in __asan_memcpy (/home/sudhakar/fuzz/libigl-fuzz/bin/101_FileIO+0x494df7)
    #2 0x4ce488 in igl::MshLoader::parse_nodes(std::basic_ifstream<char, std::char_traits<char> >&) /home/sudhakar/fuzz/libigl/include/igl/MshLoader.cpp:135:4
    #3 0x4cd0a3 in igl::MshLoader::MshLoader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sudhakar/fuzz/libigl/include/igl/MshLoader.cpp:93:13
    #4 0x4c7c53 in main /home/sudhakar/fuzz/libigl/tutorial/101_FileIO/main.cpp:13:24
    #5 0x7fa430e9dbf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #6 0x41d179 in _start (/home/sudhakar/fuzz/libigl-fuzz/bin/101_FileIO+0x41d179)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-S9d2JN/glibc-2.27/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:145 in memcpy
==18854==ABORTING
```

This is the cmake command I used to build 
```bash
export CXX=clang++-10
export CC=clang-10
export CFLAGS="-g -ggdb3 -fsanitize=address,fuzzer-no-link"
# export CFLAGS="-g -ggdb3"
export CXXFLAGS="-g -ggdb3 -fsanitize=address,fuzzer-no-link"
# export CXXFLAGS="-g -ggdb3"

$HOME/.local/bin/cmake -DLIBIGL_OPENGL=OFF -DLIBIGL_GLFW=OFF  -DLIBIGL_IMGUI=OFF  -DLIBIGL_COMISO=OFF  -DLIBIGL_EMBREE=OFF  -DLIBIGL_PNG=OFF  -DLIBIGL_COPYLEFT_CORE=OFF  -DLIBIGL_COPYLEFT_CGAL=OFF  -DLIBIGL_COPYLEFT_TETGEN=OFF  -DLIBIGL_COPYLEFT_COMISO=OFF  -DLIBIGL_RESTRICTED_TRIANGLE=OFF  -DLIBIGL_PREDICATES=OFF  -DLIBIGL_XML=OFF  -DLIBIGL_RESTRICTED_MATLAB=OFF  -DLIBIGL_BUILD_TESTS=OFF ../libigl
make -j 8
```
This is the machine I used. Its a WSL2 Ubuntu 18.04 but I don't see if that should matter.
```
[libigl-fuzz] uname -a
Linux WD-4RD07T2 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[libigl-fuzz] cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
The crashing file is 
```
[libigl-fuzz] base64 x.msh | tr -d "\n"
JE1lc2hGb3JtYXQKMi4xIDEgOAoBAAAACiRFbmRNZXNoRm9ybWF0CiROb2RlcwoxCiRFbmROb2RlcwokRWxlbWVudHMKCiRFbmRFbGVtZW50cwokTm9kZURhdGEKCiRFbmROb2RlRGF0YQokRWxlbWVudERhdGEKCiRFbmRFbGVtZW50RGF0YQo=
```
#### Platform

- [ ] Windows
- [ ] macOS
- [x] Linux

**Comment by sudhackar** [comment]
I am still actively working on the fuzzer, once stable I would raise a PR to [oss-fuzz](https://github.com/google/oss-fuzz/tree/master/projects/libigl)

**Comment by alecjacobson** [comment]
I'm not sure I understand, but I won't be personally fixing this. Feel free to submit a PR and I'd merge.
