### ISSUE TITLE
pip install libigl is looking for CMakeLists.txt where it doesn't exist

### ISSUE THREAD

**Issue by patrikhuber** [libigl/libigl#2341]
#### Describe the bug
Hi,

Doing a simple `pip install libigl` (or `pip install libigl==2.5.0`) on a PowerShell on Windows 11 results in an error. The key error line is this one - full error log further below:

It executes this:
```
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\PatrikHuber\\AppData\\Local\\Temp\\pip-install-y63mn6j5\\libigl_aa645d3a33cf494fad065f9624fe620b', '-DPYIGL_OUTPUT_DIRECTORY=C:\\Users\\PatrikHuber\\AppData\\Local\\Temp\\pip-install-y63mn6j5\\libigl_aa645d3a33cf494fad065f9624fe620b\\build\\lib.win-amd64-cpython-312\\igl', '-DPYTHON_EXECUTABLE=C:\\Users\\PatrikHuber\\PycharmProjects\\Playground\\.venv\\Scripts\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64']' returned non-zero exit status 1.
``` 

But...:
```
CMake Error: The source directory "C:/Users/PatrikHuber/AppData/Local/Temp/pip-install-y63mn6j5/libigl_aa645d3a33cf494fad065f9624fe620b" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
```

So it simply looks like the directory where it's executing cmake on doesn't contain a CMakeLists.txt.

```
(.venv) C:\Users\PatrikHuber\PycharmProjects\Playground> python --version
Python 3.12.1
(.venv) C:\Users\PatrikHuber\PycharmProjects\Playground> cmake --version
cmake version 3.28.0
```

Full command-line output:
```
(.venv) C:\Users\PatrikHuber\PycharmProjects\Playground> pip install libigl==2.5.0
Collecting libigl==2.5.0
  Using cached libigl-2.5.0.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\patrikhuber\pycharmprojects\playground\.venv\lib\site-packages (from libigl==2.5.0) (1.26.3)
Collecting scipy (from libigl==2.5.0)
  Using cached scipy-1.11.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached scipy-1.11.4-cp312-cp312-win_amd64.whl (43.7 MB)
Building wheels for collected packages: libigl
  Building wheel for libigl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for libigl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\igl
      copying igl\helpers.py -> build\lib.win-amd64-cpython-312\igl
      copying igl\_version.py -> build\lib.win-amd64-cpython-312\igl
      copying igl\__init__.py -> build\lib.win-amd64-cpython-312\igl
      running build_ext
      CMake Warning:
        Ignoring extra path from command line:

         "C:\Users\PatrikHuber\AppData\Local\Temp\pip-install-y63mn6j5\libigl_aa645d3a33cf494fad065f9624fe620b"


      CMake Error: The source directory "C:/Users/PatrikHuber/AppData/Local/Temp/pip-install-y63mn6j5/libigl_aa645d3a33cf494fad065f9624fe620b" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      Traceback (most recent call last):
        File "C:\Users\PatrikHuber\PycharmProjects\Playground\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\PatrikHuber\PycharmProjects\Playground\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\PatrikHuber\PycharmProjects\Playground\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 144, in <module>
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\PatrikHuber\AppData\Local\Temp\pip-build-env-3wu63p93\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 34, in run
        File "<string>", line 112, in build_extension
        File "C:\Users\PatrikHuber\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\PatrikHuber\\AppData\\Local\\Temp\\pip-install-y63mn6j5\\libigl_aa645d3a33cf494fad065f9624fe620b', '-DPYIGL_OUTPUT_DIRECTORY=C:\\Users\\PatrikHuber\\AppData\\Local\\Temp\\pip-install-y63mn6j5\\libigl_aa645d3a33cf494fad065f9624fe620b\\build\\lib.win-amd64-cpython-312\\igl', '-DPYTHON_EXECUTABLE=C:\\Users\\PatrikHuber\\PycharmProjects\\Playground\\.venv\\Scripts\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libigl
Failed to build libigl
ERROR: Could not build wheels for libigl, which is required to install pyproject.toml-based projects
```

#### Platform
- [x] Windows
- [ ] macOS
- [ ] Linux

**Comment by alecjacobson** [comment]
Do you _want_ to be building from source rather than using a precompiled binary?

If not, do you know why you're not getting a binary delivered?

**Comment by patrikhuber** [comment]
Thanks for the quick reply Alec!

I'm happy with a binary! However pip is not giving me a binary because [it looks like](https://pypi.org/project/libigl/2.5.0/#files) there is no binary yet for Python 3.12 on Windows (or for any platform, for that matter).

I can downgrade to Python 3.11 if it's easiest (but I'd like to rather avoid it).

**Comment by patrikhuber** [comment]
(Can confirm it fetches the precompiled binary on Python 3.11 as expected. So all good for now, but hope to see Python 3.12 support soon :) It would also be amazing to be able to do `pip install git+https://github.com/libigl/libigl@main` to compile a wheel, in case you need a fix from the latest main or something like that, but that obviously doesn't work yet because of the lack of a `setup.py` or `pyproject.toml` in the root. It should be fairly easy to accomplish though, since you are probably already building the precompiled wheels using `setup.py` or similar?)

**Comment by alecjacobson** [comment]
It seems like it's still nontrivial to enable python 3.12 on the github actions (that's where I get the wheels binaries). If you want to take a crack at it https://github.com/libigl/libigl-python-bindings/pull/221 I'm happy to merge a PR if you figure it out.

**Comment by patrikhuber** [comment]
Interesting! One of my previous students worked on a PR for a library of mine a couple of months ago https://github.com/patrikhuber/eos/pull/361, and Python 3.12 builds with cibuildwheel worked even back then. I'm not currently able to dig much deeper, but our GH Actions scripts look similar to some degree, and I didn't immediately spot something why it would work in our Actions script but not in libigl's.

**Comment by JulianKnodt** [comment]
I've also encountered this, while trying to install libigl (pip install libigl) on a Mac M2, with python 3.13.2. Has this issue been updated since last year? I could take a stab at it when I have more time (maybe in a few weeks or so)

**Comment by alecjacobson** [comment]
Good to know. Will make the main version bump soon
